name: Octave Build

on:
  pull_request:
    paths:
    - "**.m"
    - ".github/workflows/build-test-octave.yaml"
  schedule:
      - cron: "30  1  *  *  1"

# note: this test uses a docker image with the latest gnu octave installed. The
# octave images are maintained by https://github.com/gnu-octave/docker and this
# action will fetch from docker hub, https://hub.docker.com/r/gnuoctave/octave
# to pin to a particular version, replace the image value below with, e.g.,
# gnuoctave/octave:8.3.0
jobs:
  test-on-octave:
    name: Octave build
    runs-on: ubuntu-latest
    container:
      image: gnuoctave/octave
    steps:
    - uses: actions/checkout@v4
    - name: Check octave installation
      run: octave --eval "disp(version)"
    - name: Run tests
      run: octave --eval "run_all_tests"
